# Generated by Django 4.0.5 on 2022-07-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpages',
            name='topic_name',
        ),
        migrations.DeleteModel(
            name='AccessRecords',
        ),
        migrations.DeleteModel(
            name='Webpages',
        ),
    ]
